name: PermissionPortals
version: '${project.version}'
main: me.ogali.permissionportals.PermissionPortals
api-version: 1.13
softdepend:
  - Vault
commands:
  pportalsadmin:
    aliases:
      - ppa
  permissionportals:
    aliases:
      - pportals